[phases.setup]
nixPkgs = ["python39"]
depsPath = "requirements.txt"

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "./start.sh"
