[phases.setup]
nixPkgs = ["python312"]
depsPath = "requirements.txt"

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["chmod +x start.sh", "python --version", "pip --version"]

[start]
cmd = "bash start.sh"
