[phases.setup]
nixPkgs = ["python39"]
depsPath = "requirements.txt"

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt", "chmod +x start.sh"]

[phases.build]
cmds = ["echo 'Build complete'", "chmod +x start.sh"]

[start]
cmd = "./start.sh"
