[phases.setup]
nixPkgs = ["python312"]
depsPath = "requirements.txt"

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt", "chmod +x start.sh"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "bash start.sh"
