[phases.setup]
nixPkgs = ["python312"]
depsPath = "requirements.txt"

[phases.install]
cmds = []

[phases.build]
cmds = ["python -m ensurepip --upgrade", "python -m pip install --upgrade pip", "python -m pip install -r requirements.txt", "chmod +x start.sh"]

[start]
cmd = "bash start.sh"
